### ISSUE TITLE
questions about the code

### ISSUE THREAD

**Issue by YangLing0818** [RecklessRonan/glognn#1]
I ran the code, the error "No module named 'struc_sim'" came up, could you please help me to fix it? Thanks.

**Comment by RecklessRonan** [comment]
Hi~
You can get 'struct_sim' from the WRGAT repository:
https://github.com/susheels/gnns-and-local-assortativity/tree/main/struc_sim

**Comment by YangLing0818** [comment]
And another error came up "ImportError: cannot import name 'evaluate_wrgat' from 'data_utils'", could you please help me to fix it? Thanks.

**Comment by RecklessRonan** [comment]
Thanks for your attention!
We have updated 'data_utils' and added 'evaluate_wrgat'.
